Stream prev_tx after confirmation
trezor/trezor-firmware pull request #1218
Opened 2020-08-24 08:54 UTC by andrewkozlik

Implements https://github.com/trezor/trezor-firmware/issues/1109.

This PR moves the prev_tx checking code so that it is executed after the user confirms all the dialogs. To make sure that an attacker does not change the inputs after confirmation, the inputs are hashed in both stages and the hashes are compared.

I would like at least two pairs of eyes to look at the code changes in both core and legacy. Someone also make sure to look at the changes in device tests. Although 99 % of them are trivial, there are a few simulated attacks which needed to be tweaked.

2020-08-26 14:15 UTC, onvej-sl approved these changes
I reviewed both the core and legacy except the tests and it looks good to be.

2020-09-01 11:59 UTC, matejcik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
There's code in Decred to allow using undefined amount, and, curiously enough, the network accepts a transaction where the amount is unspecified.

(not sure what exactly is going on, but presumably the correct amount is signed and the `amount` field in serialization is transparently recomputed?)

However this PR disables that anyway. So the vestiges of that should be removed as well.

2020-09-01 12:01 UTC, matejcik requested changes
I reviewed core and tests. I'll do legacy another day, or leave that to someone else :)

I have some minor comments, overall seems OK.

2020-09-02 16:15 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +        self.h_inputs = bytes()
If I make it `Optional[bytes]` won't there be issues with mypy complaining that the value could be `None`, requiring extra code to ensure it's not `None`?

2020-09-02 16:17 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
> this should be ensured in `helpers.request_tx_input`, or rather `sanitize_tx_input` -- there is no longer a case where amount is not required, right?

When streaming prev tx inputs, there is no reason to require the amount.

2020-09-02 16:21 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
We could have two functions `request_tx_input()` and `request_prev_tx_input()` which would differ in the sanitization, but doesn't seem worth it. I was also considering that we could determine whether to check the amount in `sanitize_tx` depending on whether `tx_req.details.tx_hash` was set, but I think there might soon be a situation where `tx_hash` is set and we do want the amount field to be supplied.

2020-09-02 16:34 UTC, andrewkozlik commented on legacy/firmware/signing.c
> +        if (!input.has_amount || input.amount != tx->bin_outputs[0].amount) {
Meant as a failsafe, but probably pointless. Removed.

2020-09-03 08:58 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +        self.h_inputs = bytes()
Actually, I see that `h_inputs` is only used in a `!=` expression, so that won't cause any mypy issues. Done.

2020-09-03 11:38 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
That should work, but what about this?
https://github.com/trezor/trezor-firmware/blob/b2f659f979f3e5a7eec21980a647f04a117316ea/core/src/apps/bitcoin/sign_tx/bitcoin.py#L289-L291
Do we check `== 0` or do we silently produce an invalid signature?

2020-09-03 11:41 UTC, matejcik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
at this point the amount should already have been checked, no?

2020-09-03 11:47 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
It was checked in Step 3, but this is Step 6, technically the host could send `None` here.

2020-09-03 11:57 UTC, matejcik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
true, but that reduces to the case "host sends amount A for verification and amount B for signing"
so I say let's make a silently invalid signature

2020-09-03 12:03 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
https://github.com/trezor/trezor-firmware/pull/1218/commits/9b8fef91bb4491165624e42c51b753e9ccfd8291

2020-09-03 12:03 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
https://github.com/trezor/trezor-firmware/pull/1218/commits/9b8fef91bb4491165624e42c51b753e9ccfd8291

2020-09-03 14:41 UTC, matejcik commented
Reviewed the legacy code also. LGTM to the best of my understanding of the legacy signing code -- which is, admittedly, not that good.

2020-09-03 15:55 UTC, andrewkozlik commented on core/src/apps/bitcoin/sign_tx/bitcoin.py
> +            if txi.amount is None:
> The code for prevtx shouldn't be affected, we can get rid of these ifs, and if someone fails to send amount, they'll fail out with "invalid amount", which is correct.

Actually, it reports "Not enough funds".

2020-09-04 12:36 UTC, merged