Increase minimum auto-lock delay to 1 minute
trezor/trezor-firmware pull request #1354
Opened 2020-11-18 23:03 UTC by mmilata

Fixes #1351. Core + legacy.

Upgrade: if storage has <1minute the effective value is 1 minute. Less than one minute cannot be set.
Downgrade: the new set of valid timeouts is subset of the old one so downgrade should always be safe.

We've discussed lowering the minimum if `experimental_features` is set but I haven't implemented this (yet). Is it something that would make life easier for @trezor/qa?

2020-11-18 23:11 UTC, prusnak requested changes

2020-11-18 23:11 UTC, prusnak commented on legacy/firmware/config.h
> +#define MIN_AUTOLOCK_DELAY_MS (60 * 1000U)  // 10 seconds
```suggestion
#define MIN_AUTOLOCK_DELAY_MS (60 * 1000U)  // 1 minute
```

2020-11-18 23:54 UTC, mmilata commented on legacy/firmware/config.h
> +#define MIN_AUTOLOCK_DELAY_MS (60 * 1000U)  // 10 seconds
Uhh, fixed in fc3483b.

2020-11-19 08:43 UTC, prusnak approved these changes

2020-11-19 09:52 UTC, matejcik commented
by my count, this patch adds 11 minutes to the test run, which is a lot.

Basing this on `experimental_features` seems fiddly and not what that option is supposed to do though. How about we allow 10 secs for debug builds and 1 minute for production?

2020-11-19 11:39 UTC, mmilata commented
Updated to use 10s for debug builds and 1m for production builds.

2020-11-19 11:41 UTC, matejcik approved these changes

2020-11-20 11:59 UTC, tsusanka commented
Please squash and let's merge this. Two approves are enough :).

2020-11-20 12:57 UTC, prusnak approved these changes

2020-11-20 12:57 UTC, merged

2020-11-20 13:44 UTC, mmilata commented
Forgot changelog entry: #1360