fix(python): append checksum to descriptors
trezor/trezor-firmware pull request #1445
Opened 2021-02-03 15:40 UTC by prusnak

Descriptors contain optional checksum. Let's compute it at and append it to the descriptor.

2021-02-05 09:43 UTC, matejcik requested changes

2021-02-05 09:43 UTC, matejcik commented on python/src/trezorlib/tools.py
> +def descriptor_checksum(desc: str) -> str:
please also add a testcase or three for this to `python/tests`

2021-02-05 10:07 UTC, matejcik approved these changes

2021-02-05 16:46 UTC, merged

2021-03-11 14:41 UTC, KaycoinsInc approved these changes

2021-03-11 14:42 UTC, KaycoinsInc approved these changes

2021-03-11 14:42 UTC, KaycoinsInc approved these changes