fix(debug): fix show-text import and parameter exceptions
trezor/trezor-firmware pull request #1522
Opened 2021-03-07 02:06 UTC by mcudev

i was testing the usb debug stuff and noticed that this had a stale import. after that was fixed, an exception was due to the positional parameter to `Success`.

reproduce with:

`trezorctl debug show-text blah`

2021-03-07 09:33 UTC, prusnak commented on core/src/apps/debug/show_text.py
> +import trezor.ui.components.common.text as text
Seems like this should be `components.tt.text` (that's what we use in the rest of the codebase) - but let's wait for @matejcik - he knows more than me on this topic

```suggestion
import trezor.ui.components.tt.text as text
```

but I

2021-03-08 08:58 UTC, matejcik commented
i'm somewhat tempted to throw this code out completely, I don't think we will need it anymore. let's discuss that on standup

2021-03-08 12:18 UTC, mcudev commented
i only came across this because i was trying to test the debug usb interface with trezorctl. after looking deeper, trezorctl was using the wire interface anyways, and so was not testing what i wanted to.

2021-03-13 14:33 UTC, AaronWashington requested changes
> ``

2021-03-17 15:10 UTC, matejcik commented
closing in favor of #1531

2021-03-17 15:10 UTC, closed without merging