Drbg rework (part 1)
trezor/trezor-firmware pull request #1554
Opened 2021-03-29 11:37 UTC by onvej-sl

This PR replaces https://github.com/trezor/trezor-firmware/pull/1481.

The purpose of this PR is to replace hmac_drbg (that is used by random interrupts and `wait_random`) with faster chacha_drbg.

2021-03-29 11:44 UTC, onvej-sl commented
These are comments unresolved in the original PR that are hopefully resolved in this PR:
https://github.com/trezor/trezor-firmware/pull/1481#discussion_r578536056
https://github.com/trezor/trezor-firmware/pull/1481#discussion_r586517905
https://github.com/trezor/trezor-firmware/pull/1481#discussion_r593026121

2021-05-04 09:44 UTC, andrewkozlik requested changes
It still doesn't make sense to me why the original pull request was closed after having been extensively reviewed. I had to redo this entire review from scratch and there is more to come. Terribly inefficient.

2021-05-05 12:22 UTC, onvej-sl commented on legacy/random_delays.h
> +#define __RANDOM_DELYAS_H__
20f91a71ac61329a8229ad44cd3c79382340df9e

2021-05-05 12:22 UTC, onvej-sl commented on core/embed/trezorhal/random_delays.c
> +  static volatile atomic_flag locked = {0};
d1164f485a291227bb00dd184f67a7f14ca4bcc5

2021-05-05 12:22 UTC, onvej-sl commented on core/embed/trezorhal/random_delays.c
> +static uint32_t drbg_random8(void) {
d1164f485a291227bb00dd184f67a7f14ca4bcc5

2021-05-05 12:22 UTC, onvej-sl commented on core/embed/trezorhal/random_delays.c
> +void rdi_start(void) {
Definitely.

Done in d1164f485a291227bb00dd184f67a7f14ca4bcc5.

2021-05-10 14:48 UTC, andrewkozlik approved these changes

2021-05-21 11:42 UTC, merged