fix(legacy): make intermediate firmware not to erase firmware and storage
trezor/trezor-firmware pull request #1600
Opened 2021-05-05 15:41 UTC by prusnak

Possible fix for https://github.com/trezor/trezor-firmware/issues/1597

2021-05-06 13:54 UTC, matejcik approved these changes
looks good, as best as I can tell

2021-05-06 17:02 UTC, kusai90 reviewed
#

2021-05-07 17:56 UTC, hiviah approved these changes
Looks fine, but I didn't get chance to test it on device.

2021-05-10 10:36 UTC, prusnak commented
Switching back to draft - we need to polish the details before merging this one in.

2021-05-12 09:46 UTC, andrewkozlik commented on legacy/intermediate_fw/trezor.c
> +static const uint32_t META_MAGIC_V10 = 0x525a5254;   // 'TRZR'
Yes this is correct. `NORCOW_MAGIC_V0` "NRCW" was used only on Trezor T before firmware 2.1.0.

2021-05-12 13:17 UTC, andrewkozlik requested changes
Please use [fixup commits](https://docs.trezor.io/trezor-firmware/misc/review.html#review-process). They make it easier to review.

2021-05-12 13:46 UTC, andrewkozlik commented on legacy/intermediate_fw/trezor.c
> +  // Erase storage sectors
I think you are correct that we don't need to erase the storage here.

2021-05-12 15:18 UTC, prusnak commented on legacy/intermediate_fw/trezor.c
> +             sizeof(NORCOW_MAGIC)) == 0 ||
Addressed in 8f9acc873e0da66d236be5f58fd83181a09f90b1

2021-05-12 15:43 UTC, andrewkozlik approved these changes
utACK

2021-05-12 16:01 UTC, prusnak commented on legacy/intermediate_fw/trezor.c
> +  // Erase storage sectors
Ok, addressed in another fixup - b4c7d22806a74cf3c073b85fb06f787d18baac83

2021-05-12 16:10 UTC, andrewkozlik approved these changes

2021-05-13 14:43 UTC, onvej-sl approved these changes

2021-05-13 15:59 UTC, merged