Avoid accidental build with broken stack protector, especially for bundled bootloader.bin
trezor/trezor-firmware pull request #1642
Opened 2021-06-02 14:38 UTC by hiviah

Per https://blog.inhq.net/posts/faulty-stack-canary-arm-systems/ ARM gcc versions 9.2.1-10.2 have broken stack smash protector. Unfortunately these are still included in distros.

The main purpose of the PR is to prevent build of bootloader.bin with broken gcc which gets bundled with firmware since that is done usually manually and not in CI.

2021-06-03 13:30 UTC, invd commented
As discussed directly, I think this is a decent approach.

It is likely that there will be fixed backports of GCC for ARM without the stack canary compiler issue some time in the future, at which point the checks may need some adjusting, but I think this is acceptable.

For the record, to my knowledge only  the original `10.2` release (so `10.2.0`) is affected. `10.2.1` is the first fixed version.
AFAIK the current check is correct, I'm primarily mentioning this since `10.2` can also be misunderstood as the whole `10.2.x` series.

2021-06-03 13:40 UTC, prusnak commented
> I'm primarily mentioning this since `10.2` can also be misunderstood as the whole `10.2.x` series.

Addressed in 240891e9e2ebfb8160e3efd1c52f5869aed2827b

Thanks for spotting this.

2021-09-23 10:32 UTC, matejcik commented
what is the reason this is a draft? @hiviah @prusnak

2021-09-27 10:58 UTC, prusnak requested changes
I just noticed we changed the comment, but not the error messages itself. Left 2 suggestions. ACK once these 2 have been addressed.

2021-09-27 10:58 UTC, prusnak commented on core/embed/trezorhal/compiler_traits.h
> +    "ARM GCC versions 9.2.1 - 10.2 have broken stack smash protector, aborting build."
```suggestion
    "ARM GCC versions 9.2.1 - 10.2.0 have broken stack smash protector, aborting build."
```

2021-09-27 10:58 UTC, prusnak commented on legacy/compiler_traits.h
> +    "ARM GCC versions 9.2.1 - 10.2 have broken stack smash protector, aborting build."
```suggestion
    "ARM GCC versions 9.2.1 - 10.2.0 have broken stack smash protector, aborting build."
```

2021-09-27 11:49 UTC, prusnak approved these changes

2021-09-27 13:42 UTC, merged