fix(tests): decoding PNG files to fix Linux/Mac differences in encoding
trezor/trezor-firmware pull request #1795
Opened 2021-09-02 11:06 UTC by grdddj

Addressing https://github.com/trezor/trezor-firmware/issues/1769:
- when creating a file hash for UI fixtures, accounting for possible difference in PNG encoding algorithm (between Linux and Mac), so decoding the "real" image data and hashing them instead, to be consistent on both platforms

2021-09-02 11:13 UTC, matejcik requested changes
please also regenerate the fixtures so that someone can check that they come out the same on Mac

2021-09-02 11:13 UTC, matejcik commented on tests/ui_tests/__init__.py
> +from helpers import get_bytes_from_png
use relative import, presumably from `.helpers` should work

2021-09-02 11:13 UTC, matejcik commented on tests/ui_tests/helpers.py
> +def get_bytes_from_png(png_file: str) -> bytes:
instead of implementing raw PNG reading (fragile), please use the Pillow library which we already have in dependencies

2021-09-02 11:13 UTC, matejcik commented on tests/ui_tests/helpers.py
> +def get_bytes_from_png(png_file: str) -> bytes:
this seems suitable: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.tobytes

2021-09-02 11:13 UTC, matejcik commented on tests/ui_tests/helpers.py
> +def get_bytes_from_png(png_file: str) -> bytes:
Pillow-based impl should be small enough so that you don't need to create a new file for it, i think?

2021-09-02 12:39 UTC, grdddj commented
Thanks for the suggestions, the latest force-push includes the simplifications and regenerated `fixtures.json`, so it can be tried by somebody with Mac

2021-09-02 12:49 UTC, matejcik commented
@prusnak can you confirm that Mac produces the same hashes now?

2021-09-02 13:08 UTC, prusnak commented
I tried the changes on macOS and it seems this helped for some cases (e.g. `test_u2f_counter.py`) but did not help for others (e.g. `test_op_return.py`).

I guess that

![](https://i.kym-cdn.com/photos/images/newsfeed/000/531/557/a88.jpg)

2021-09-02 13:10 UTC, matejcik commented
can you upload the recorded directory somewhere?

2021-09-02 13:24 UTC, prusnak commented
here: [screens.zip](https://github.com/trezor/trezor-firmware/files/7099133/screens.zip)

2021-09-03 08:47 UTC, grdddj commented
Thanks for providing the screenshots, there is a **difference between the UI screenshots** themselves from what I can see.

Below is the comparison of `test_opreturn`, first in "my" Linux environment and second in "Mac" - there are more screens there.

Hash of Linux one is `592e849159d5e02fed1c353030089106213951876221bd1d67e12b6ac8c3d077` and when I do hashing of the Mac screenshots, I get `a607ae83192cf7445d17270a42b9523c3865eefa18e29de1e6a608dc873cb4d4`

@prusnak - does the last hash correspond with what you are getting locally?

For the `test_u2f_counter` I also get the same hash on both screenshot folders - `19f77e2d284431da5fadac938f5822c1a6b17c07ee6c801085efd84974f3163f`

![image](https://user-images.githubusercontent.com/42543243/131976659-a57627af-cd54-4eb9-8ad9-f4b1a8231a70.png)

![image](https://user-images.githubusercontent.com/42543243/131976749-22df114e-ea5f-4994-a58b-91e5a9bb490d.png)

2021-09-03 08:54 UTC, matejcik commented
@prusnak these look like they are recorded with animations enabled.
please make sure you run `emu.py -a` for UI tests

2021-09-03 09:57 UTC, prusnak commented
> please make sure you run `emu.py -a` for UI tests

Argh! That was it.

2021-09-03 10:09 UTC, grdddj commented
> > please make sure you run `emu.py -a` for UI tests
> 
> Argh! That was it. The hashes match now.

Nice, thanks for verifying.

One other thing seems to be broken, the CI Pipeline's last step failed for some reason connected with UI tests:
https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1557001773

2021-09-03 10:12 UTC, prusnak commented
It seems this PR is not necessary after all - it was my fault for not disabling the animations when generating the fixtures. 🤦 

However, I'd still merge the changes because SDL can optionally be linked against macOS-shipped PNG encoder and we might hit this issue again later.

2021-09-03 10:19 UTC, grdddj commented
> It seems this PR is not necessary after all - it was my fault for not disabling the animations when generating the fixtures. facepalm
> 
> However, I'd still merge the changes because SDL can optionally be linked against macOS-shipped PNG encoder and we might hit this issue again later.

From this https://github.com/trezor/trezor-firmware/pull/1683#issuecomment-901892448 it seems even with animations disabled, the hashes still differed between Linux/Mac

The disadvantage of merging it could be higher computational overhead of having to decode PNG, but these things are running on servers/computers and not on Trezor, so no big slowdown.

2021-09-03 10:20 UTC, matejcik commented
@gabrielKerekes could you verify that (a) you can still reproduce the problem with UI fixtures on a Mac, and (b) this PR solves it?

2021-09-03 10:26 UTC, matejcik commented
> One other thing seems to be broken, the CI Pipeline's last step failed for some reason connected with UI tests:
> [gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1557001773](https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1557001773)

this is caused by an earlier failure that was not reported: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1557001748

the `prepare_ui_artifacts.py` file has its own copy of `_hash_files`.

@grdddj please modify the file so that it uses `_hash_files` from `tests.ui_tests`. It might be sufficient to do `from tests.ui_tests import _hash_files`; if not, you'll need to do some `sys.path` trickery.

2021-09-03 10:29 UTC, matejcik commented
you can also use other things from `tests.ui_tests`, namely `FILE_HASHES` (after calling `read_fixtures()` and `UI_TESTS_DIR / "screens"`

2021-09-03 11:18 UTC, grdddj commented
> this is caused by an earlier failure that was not reported: https://gitlab.com/satoshilabs/trezor/trezor-firmware/-/jobs/1557001748

Does it also mean we will need to do something  with this, so next time the AssertionError will fail the CI?

2021-09-03 11:29 UTC, matejcik commented
That's a good idea, but i'm not sure what. Can you look into it?

2021-09-03 11:32 UTC, grdddj commented
> That's a good idea, but i'm not sure what. Can you look into it?

Sure. I imagine we could be somehow catching the errors in the definition of `core device ui test` CI stage

2021-09-03 11:42 UTC, grdddj commented
So it turns out this UI artifacts are being run in `after_script`, which does not fail the job, even if the script fails

Possibility:
- adding all the `after_script` stuff into `script`

https://github.com/trezor/trezor-firmware/blob/6f1005b155a7d79482dfee33506f7892b4e81c48/ci/test.yml#L12-L20

2021-09-07 20:48 UTC, gabrielKerekes commented
> @gabrielKerekes could you verify that (a) you can still reproduce the problem with UI fixtures on a Mac, and (b) this PR solves it?

I can confirm that by checking out a previous commit (cec1f39a90b8eff65fa2672f258829464ba28fd0) and running `pytest tests/device_tests -m cardano --ui=record` all the Cardano hashes changed. With this branch checked out no fixtures changed. I also tried changing how a stake delegation certificate is displayed and only the hashes of fixtures containing the certificate changed. So this PR does solve the problem 👍

2021-09-08 08:12 UTC, matejcik approved these changes
perfect, thanks for testing.

@grdddj please squash the fixups and rebase on current master so we can get it merged.

let's leave the CI issue aside now, it's unlikely that we would run into it again

2021-09-14 12:21 UTC, merged