perf(legacy/bootloader): use slow but small implementation of bn_inverse
trezor/trezor-firmware pull request #1951
Opened 2021-11-26 18:56 UTC by onvej-sl

|            | bootloader size | `ecdsa_verify_digest` time |
|------------|-----------------|----------------------------|
| before     | 32760 B         | 230 ms                     |
| after      | 32060 B         | 390 ms                     |
| difference | -700 B          | +160 ms                    |

The execution times were measured on TT in python and multiplied by `168/120`. The bootloader verifies 3 signatures on startup, which means the total execution time increases from 700 ms to 1200 ms.

Do you think it's worth it?

2021-11-27 01:10 UTC, hiviah requested changes
I'd really want not to use this shortcut, even though I am thankful you've found it. Unless really necessary.

2021-11-27 01:46 UTC, hiviah commented
OTOH -700 B saved on bootloader size and only + 160ms added time could be palatable.

2021-11-27 10:24 UTC, prusnak commented
Let's keep this open as a reminder and not merge this right now.

2021-11-30 08:38 UTC, prusnak commented
Let's close this in favor of https://github.com/trezor/trezor-firmware/pull/1957 which has been merged already.

2021-11-30 08:38 UTC, closed without merging

2021-12-05 06:31 UTC, Afsoning approved these changes