feat: add Cardano testnet definitions
trezor/trezor-firmware pull request #2016
Opened 2021-12-14 14:52 UTC by vladimirvolek

2021-12-14 15:27 UTC, prusnak requested changes

2021-12-14 15:27 UTC, prusnak commented on common/defs/misc/misc.json
> +        "slip44": 1815,
Every testnet should use 1 for SLIP44.

```suggestion
        "slip44": 1,
```

2021-12-14 15:29 UTC, matejcik commented
Why do you need this? Just to display `tADA` on trezor.io/coins ?

2021-12-15 11:17 UTC, mroz22 commented
> Why do you need this? Just to display `tADA` on trezor.io/coins ?

Connect runs this script https://github.com/trezor/connect/blob/develop/scripts/coins-build.sh in order to generate coins.json file which is later used in connect runtime. My understanding is that without the change proposed here, we won't have cardano testnet in the resulting json file.

2021-12-15 11:21 UTC, matejcik commented
there are missing support infos
please add them, see https://github.com/trezor/trezor-common/tree/filter-repo/tools#maintaining-support-status

2021-12-15 13:09 UTC, matejcik approved these changes

2021-12-15 13:10 UTC, merged