Increase clock frequency to 180 MHz
trezor/trezor-firmware pull request #2587
Opened 2022-10-26 19:20 UTC by TychoVrahe

Increases CPU frequency to 180MHz for TT (and models based on STM32F42x)

On TT: for compatibility between older firmware/new bootloader and vice verse when switching layers the frequency is returned to original 168MHz.

Other models: frequency is set in boardloader.

Also the configuration for F405 / 120MHz was wrong, so i fixed that (wasn't used anywhere since T1 isnt using core boardloader).

2022-10-31 09:00 UTC, TychoVrahe commented
in the fixup, i adjusted HSE division to achieve prescribed 1-2MHz VCO input frequency

2022-11-01 16:17 UTC, hiviah requested changes
Seems that the clock changes work as expected on device, but we should

* put the `set_core_clock` into a header instead of having it as extern everywhere
* add comment to the function which clocks it sets how depending on parameter - main 168/180MHz, USB 48 MHz, do we use any other clock in clock network for display or something else based on this (?)

2022-11-01 21:40 UTC, TychoVrahe commented
@hiviah : https://github.com/trezor/trezor-firmware/pull/2587/commits/e5fe5e1f3ead7bbf26a7dab052923c2e64f8441d
1. added the header
2. tried to make the clock setting clearer and more versatile, inspired by how its done in legacy. unfortunately it still needs the defines since the config array is statically initialized after the SystemInit function runs for first time in boardloader. Let me know if this is better.
Basically all clocks are derived from the core clock, notably it affects:
SysTick - is reconfigured 
PWM for backlight - will be slightly faster, changing the configuration anyway here https://github.com/trezor/trezor-firmware/pull/2595
I2C for touch - will be slightly faster, currently set to 200kHz, the range is 10kHz-400kHz. Isn't reconfigured - the real frequency will be a bit different from what is in initialization. Maybe we should do the reconfig here, what do you think?
FMC for display data - will be slightly faster, seems to work fine
SDIO comm - will be slightly faster, seems to work fine
RGB LED on model R - i was actually counting with 180 MHz back then so this is corrected

Let me know if you can think of anything else that might be affected

2022-11-02 12:43 UTC, hiviah approved these changes
Retested, LGTM

2022-11-04 14:10 UTC, merged