v3 signmessage fw parsing in trezorlib
trezor/trezor-firmware pull request #2701
Opened 2022-12-20 14:09 UTC by matejcik

introduces the necessary pieces for validation of v3-signed T1 firmwares

will cause a conflict with #2649 -- @TychoVrahe please remove the piece touching trezorlib because it's already included here

2022-12-27 21:01 UTC, TychoVrahe requested changes
needs fixing validation of  legacy V3 DEV signatures

2022-12-27 21:01 UTC, TychoVrahe commented on python/src/trezorlib/firmware/models.py
> +    firmware_sigs_needed=2,
the signing script in debug_signatures actually fill all three signatures, which causes the validation to fail. we should increase this to 3 or modify the script

2022-12-28 12:31 UTC, TychoVrahe commented on python/src/trezorlib/firmware/models.py
> +    firmware_sigs_needed=2,
will be handled elsewhere

2022-12-28 12:49 UTC, matejcik commented on python/src/trezorlib/firmware/legacy.py
> +            models.TREZOR_ONE_V3.firmware_sigs_needed,
[e4a08a8](https://github.com/trezor/trezor-firmware/pull/2701/commits/e4a08a86ca96987d14b5751db3ab1bf417d6b391)

2022-12-28 12:49 UTC, matejcik commented on python/src/trezorlib/firmware/legacy.py
> +            models.TREZOR_ONE_V1V2.firmware_sigs_needed,
[e4a08a8](https://github.com/trezor/trezor-firmware/pull/2701/commits/e4a08a86ca96987d14b5751db3ab1bf417d6b391)

2022-12-28 12:50 UTC, matejcik commented on python/src/trezorlib/_internal/firmware_headers.py
> +                fw_models.TREZOR_T.boardloader_sigs_needed,
[b729b16](https://github.com/trezor/trezor-firmware/pull/2701/commits/b729b167cea17671c6faae0870150ed9174fc398)

2022-12-29 10:24 UTC, merged