feat: Upgrade to isort 5.12.0
trezor/trezor-firmware pull request #2893
Opened 2023-03-20 17:37 UTC by AdarshRawat1

2023-03-20 17:38 UTC, AdarshRawat1 commented
#2173

2023-03-24 11:23 UTC, matejcik requested changes
thank you for your work, this is shaping up nicely.

please look into tweaking the isort config as indicated, and revert some of the changes. it might actually be better if you only include files covered by `make pystyle` (as opposed to every .py file in the project)

2023-03-24 11:23 UTC, matejcik commented on ci/common_sync/git-filter-repo
please revert this

2023-03-24 11:23 UTC, matejcik commented on core/tests/test_apps.bitcoin.address.py
> +from common import *
we actually need "common" to be first. but maybe this is not worth worrying about, just reverting the whole of `core/tests` is good enough

2023-03-24 11:23 UTC, matejcik commented on core/tests/production_tests/main.py
> +import utime
utime should also be in the "system builtins" group

2023-03-24 11:23 UTC, matejcik commented on tests/bip32.py
>  from trezorlib import messages, tools
generally we want "trezorlib" to always be in the "1st party" section or whatever it is called, i.e., separated from click / pytest / ecdsa / etc.
there should be no diff here and in 90 % of `tests/`

2023-03-24 11:23 UTC, matejcik commented on setup.cfg
> -known_first_party = trezorlib,apps
it looks like the new isort is good enough to figure out the "3rd party" stuff on its own, but we would like to keep both `known_standard_library` and `known_first_party`, see the other comments

2023-03-26 05:17 UTC, AdarshRawat1 commented
@matejcik  I have made all the suggested changes.Please review!

2023-03-26 05:17 UTC, closed without merging

2023-03-26 05:18 UTC, AdarshRawat1 commented
@matejcik 
I couldn't make necessary changes on master branch as there were too many files, so I created a separate PR from different branch.