Added Avian AVN coin support (altcoin based on Bitcoin code)
trezor/trezor-firmware pull request #3961
Opened 2024-06-19 00:20 UTC by Refloow

2024-07-22 22:33 UTC, Refloow commented
Can we know if there are any additional edits needed, or do we need to provide any more data for Avian to be integrated?
Integration followed the rules & guidelines in documentation for adding altcoins based on bitcoin code.
A publication post about this pull request was made from official Avian Network twitter account: https://x.com/avianfoundation/status/1805278579162268048
Electrum would be used for wallet connectivity. Everything has been integrated, tested & finished on our end:
https://github.com/AvianNetwork/electrum-avian/releases
Looking forward to hearing from you soon, thanks in advance

2024-10-01 11:02 UTC, Hannsek commented
Hi, sorry for the delayed message. We'll merge this soon if there are no troubles.

Please also add Trezor HW as a supported wallet to [here](https://www.avn.network/en/wallets) if possible.

2024-10-01 11:39 UTC, matejcik commented
@Refloow you will want to use `./common/tools/support.py` to add support info for all models (that is currently T1B1, T2T1, T2B1, T3T1, T3B1). `support.py --help` or the readme in `common/tools` explains the process.

please also make sure `make gen` and `make style` run and the results are checked into this PR.

please rebase on top of current main so that we can get the CI results

2024-10-04 09:02 UTC, matejcik requested changes
(marking "changes requested" per the above comment)

2026-04-30 14:16 UTC, closed without merging

2026-04-30 14:16 UTC, obrusvit commented
The PR seems obsolete at this point, please reopen if there's still interest.
Thank you.