T3T1: tutorial flow
trezor/trezor-firmware pull request #3982
Opened 2024-06-26 10:05 UTC by mmilata

Fixes #3829.

Missing, to be done by end of week:
- [ ] color and icon on the first screen
- [ ] color of the hold-to-confirm screen on the "cancel" path

![emu00000000](https://github.com/trezor/trezor-firmware/assets/85857/f0bce602-d4c6-450e-827e-4131ce08c8a0) ![emu00000001](https://github.com/trezor/trezor-firmware/assets/85857/15d53fe9-c92d-4f18-be60-e5d93ec2e2bb) ![emu00000003](https://github.com/trezor/trezor-firmware/assets/85857/0b7689cb-6163-4eed-91dc-a4889dc4cb55) ![emu00000004](https://github.com/trezor/trezor-firmware/assets/85857/5cdabe98-97bc-4485-88de-7ac668966f98) ![emu00000005](https://github.com/trezor/trezor-firmware/assets/85857/50797849-4e85-4045-9bf4-b31c27b01ac2) ![emu00000006](https://github.com/trezor/trezor-firmware/assets/85857/9f26a9b7-fd40-4a2b-b7e4-1a94434f9324) ![emu00000007](https://github.com/trezor/trezor-firmware/assets/85857/40885fd8-1e9b-49c3-87b2-27cefff20c4b)

2024-06-26 11:55 UTC, obrusvit reviewed
Code is pretty straightforward.
We need to handle changed translations.

2024-06-26 11:58 UTC, Hannsek commented
Yes, there will be also some copy minor tweaks.

2024-06-26 12:13 UTC, Hannsek commented
@mmilata sorry, we've updated the copy a bit. Please go through it [here](https://www.figma.com/design/n43caWJFGJlT167AQcxruu/%E3%80%94-Prod-%E3%80%95Safe-5?m=auto&node-id=5220-1963&t=GzQ7Uem7cRBDENDG-1) and change it accordingly.

2024-06-27 15:05 UTC, mmilata commented
Fixed the colors and copy in [1fe3569](https://github.com/trezor/trezor-firmware/pull/3982/commits/1fe3569a0471e9d9491ee145699acf54bf52ed97), please take a look.

2024-06-28 15:33 UTC, obrusvit requested changes

2024-06-28 15:33 UTC, obrusvit commented on core/translations/en.json
The following strings can be removed (please remove also from `de/es/fr/cs.json`)
- `instructions__hold_to_finish_tutorial`
- `tutorial__first_transaction_intro`
- `tutorial__first_transaction_outro`
- `tutorial__one_more_step`
- `tutorial__subtitle_safe5`

2024-06-30 12:01 UTC, obrusvit approved these changes
Tested ACK.

Limitations not blocking this PR:
- HoldToConfirm danger, the filling circle is green, should probably be the same color as the danger circle
- removing the obsolete strings as my previous comment
- other langs (in progress)

2024-06-30 12:07 UTC, Hannsek commented
> HoldToConfirm danger, the filling circle is green, should probably be the same color as the danger circle

This is the same on other places as well, like Hold to wipe. Let's fix it on all places at once.

2024-06-30 13:42 UTC, obrusvit commented on core/translations/en.json
https://github.com/trezor/trezor-firmware/pull/3982/commits/0185544aec44ee975d0b0fa2ff96808e91927e60

2024-07-01 07:35 UTC, merged

2024-07-01 14:59 UTC, bosomt commented
**QA OK**

`trezorctl device tutorial`


noticed red color when canceling

<img width="231" alt="image" src="https://github.com/trezor/trezor-firmware/assets/31506317/f816f87d-70cf-4bd2-8002-f93d7f4ec894">

and differently pointing welcome screen

<img width="215" alt="image" src="https://github.com/trezor/trezor-firmware/assets/31506317/4660dbf8-b5c8-4a81-bc8c-61ee74861e4e">


 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)

2024-07-03 06:52 UTC, Hannsek commented
Both are expected.