refactor usb events
trezor/trezor-firmware pull request #4426
Opened 2024-12-06 11:03 UTC by TychoVrahe

This PR refactors how USB events (currently configured/deconfigured) are processed. 

The new system is more in line with how other events, like touch or button, are processed, and allows easier addition of more events if needed (like connected/disconnected on battery powered devices perhaps).

2024-12-09 14:23 UTC, cepetr requested changes

2024-12-10 08:47 UTC, TychoVrahe commented on core/embed/io/usb/stm32/usb.c
> +  drv->configured =
fixed along with some other occurrences in this file: https://github.com/trezor/trezor-firmware/commit/d45da636da0989b16f653ec57a42807e5867ba42

2024-12-10 08:48 UTC, TychoVrahe commented on core/embed/io/usb/stm32/usb.c
> +  if (drv->initialized != sectrue) {
fixed: https://github.com/trezor/trezor-firmware/commit/d45da636da0989b16f653ec57a42807e5867ba42

2024-12-12 06:33 UTC, cepetr approved these changes
Tested, and everything appears to be working correctly.

2025-01-13 17:46 UTC, merged