fix(core/ui): fix a bug causing marquee on model TR to not start
trezor/trezor-firmware pull request #4437
Opened 2024-12-10 14:09 UTC by matejcik

fixes #4431

2024-12-10 21:22 UTC, ibz commented
Now I understand what you said with "just return the `None`! Thank you!

2024-12-12 09:41 UTC, bieleluk commented
The change looks good to me. Tested it manually on T3B1. Device tests are not affected because the animations are disabled.
The only missing thing is entry in the core change log

2024-12-12 09:42 UTC, bieleluk requested changes
The change looks good to me. Tested it manually on T3B1. Device tests are not affected because the animations are disabled.
The only missing thing is entry in the core change log

2025-01-03 13:13 UTC, bieleluk approved these changes
Because the broke marquee was not released, the change-log is not necessary.

2025-01-03 13:24 UTC, merged

2025-01-13 15:41 UTC, bosomt commented
**QA OK**

checked in German translation with `Check device` command


**Info:**
 - Suite version: web 25.2.0 (cb718047495ced282346ffa602a324326656ddf8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.7 regular (revision 8a254aa8eae82f99630df63f40e4d290066a3efc)
 - Transport: BridgeTransport 3.0.0-bundled.25.1.1