introduce NRF and BLE drivers
trezor/trezor-firmware pull request #4448
Opened 2024-12-13 15:51 UTC by TychoVrahe

This PR introduces NRF driver, responsible for handling communication with NRF, and BLE driver, which provides interface for using BLE via the NRF.

2025-01-02 14:10 UTC, cepetr requested changes

2025-01-02 14:10 UTC, cepetr commented on core/embed/io/nrf/stm32u5/nrf.c
> +  drv->initialized = false;
We should reset the UART/SPI peripherals and disable interrupts in the NVIC controller here. If we call `nrf_deinit` in `drivers_deinit()` within the bootloader, we can also remove the `if (drv->initialized)` condition from the interrupt handlers.

2025-01-02 15:59 UTC, TychoVrahe commented on core/embed/sys/syscall/stm32/syscall_verifiers.c
> +  ble_get_state(state);
fixed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 15:59 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble_comm_defs.h
> +} InternalEvent_t;
fixed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 15:59 UTC, TychoVrahe commented on core/embed/io/nrf/inc/io/nrf.h
> +} nrf_packet_t;
removed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 16:00 UTC, TychoVrahe commented on core/embed/io/nrf/inc/io/nrf.h
> +void nrf_unregister_listener(nrf_service_id_t service);
went with the second option https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

lets add the context callback when we need it

2025-01-02 16:03 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  uint8_t urt_rx_buf[UART_PACKET_SIZE];
tried to do some renaming https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765. there is rx for both spi and uart, so there is some ambiguity, which is now resolved by calling the spi rx buffer 'long_rx_buffer', as it servers for sending longer messages, but i am not entirely sure that this was an overall improvement

2025-01-02 16:03 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  __HAL_RCC_USART3_CLK_ENABLE();
maybe, seems a bit premature though, lots of constants that we don't really need yet

2025-01-02 16:04 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +    drv->service_listeners[service] = listener;
fixed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 16:04 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  tsqueue_t urt_tx_queue;
removed urt_tx_running https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 16:04 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  bool spi_rx_running;
removed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 16:04 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +    drv->urt_sending.callback(NRF_STATUS_ERROR, drv->urt_sending.context);
fixed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

2025-01-02 16:10 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  drv->initialized = false;
fixed https://github.com/trezor/trezor-firmware/commit/bec19dae870a86a582b25fbf032ac77ddaf72765

the gpios currently stay initialized, including the AF ones

2025-01-02 21:25 UTC, mmilata commented on core/embed/io/ble/stm32/ble.c
> +  systimer_t *timer = systimer_create(ble_loop, NULL);
Would disabling the timer in `ble_deinit` (or `ble_stop`) help with energy consumption or is that premature optimization? Currently neither function is ever called.

2025-01-02 21:25 UTC, mmilata commented on core/embed/io/ble/stm32/ble.c
> +  switch (data[0]) {
Is it safe to assume that `len` > 0?

2025-01-03 10:15 UTC, cepetr requested changes

2025-01-03 10:15 UTC, cepetr commented on core/embed/io/nrf/stm32u5/nrf.c
> +  if (drv->tx_msg_id == id) {
It seems to me, this requires synchronization with the interrupt (UART_TxCpltCallback).

2025-01-03 13:04 UTC, TychoVrahe commented on core/embed/util/tsqueue/tsqueue.c
> +  } else {
fixed, thx https://github.com/trezor/trezor-firmware/commit/191fa1a026fb38d579b593ff0ccff0fe2f32bccd

2025-01-03 13:05 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  uint8_t send_buffer[NRF_MAX_TX_DATA_SIZE];
fixed https://github.com/trezor/trezor-firmware/commit/191fa1a026fb38d579b593ff0ccff0fe2f32bccd

2025-01-03 13:08 UTC, TychoVrahe commented on core/embed/io/ble/inc/io/ble.h
> +  uint8_t peer_count;
its number of bonded devices. 

currently when we advertise with whitelist we put all bonded devices there, but its not mandatory 

the intent is to use this to automatically start advertising (with whitelist) if there is at least one bonded device (but that is something that needs product decision)

2025-01-03 13:08 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  if (!nrf_is_running()) {
removed the checks here a put it into `nrf_send_msg`

2025-01-03 13:11 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  systimer_t *timer = systimer_create(ble_loop, NULL);
not sure if it affects energy consumption, but it should be stopped. https://github.com/trezor/trezor-firmware/commit/191fa1a026fb38d579b593ff0ccff0fe2f32bccd

the deinits will eventually be called when puting the device in low power mode, or when jumping between bootloader and firmware. 

but currently we don't have ble in bootloader and low power mode is waiting for https://github.com/trezor/trezor-firmware/pull/4454

2025-01-03 13:11 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  switch (data[0]) {
probably mostly safe but i added the check anyway in https://github.com/trezor/trezor-firmware/commit/191fa1a026fb38d579b593ff0ccff0fe2f32bccd

2025-01-03 13:12 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  bool read = tsqueue_dequeue(&drv->event_queue, (uint8_t *)&tmp_event,
simplified https://github.com/trezor/trezor-firmware/commit/b23337ea0879d5a0dfcf92a24a9106479e0490a8

2025-01-03 13:12 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  uint16_t read_len = 0;
fixed https://github.com/trezor/trezor-firmware/commit/b23337ea0879d5a0dfcf92a24a9106479e0490a8

2025-01-03 13:13 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  if (state == NULL) {
removed https://github.com/trezor/trezor-firmware/commit/b23337ea0879d5a0dfcf92a24a9106479e0490a8

2025-01-03 13:23 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +        tsqueue_enqueue(&drv->send_queue, data, NRF_MAX_TX_DATA_SIZE, NULL);
yeah the intention was to always only have single message buffer here. i added comment for the TX_QUEUE_LEN constant so that no one changes it accidentally 
https://github.com/trezor/trezor-firmware/commit/191fa1a026fb38d579b593ff0ccff0fe2f32bccd

2025-01-03 13:24 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  if (drv->tx_msg_id == id) {
fixed https://github.com/trezor/trezor-firmware/commit/b23337ea0879d5a0dfcf92a24a9106479e0490a8

2025-01-03 13:27 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  uint8_t urt_rx_buf[UART_PACKET_SIZE];
see commits https://github.com/trezor/trezor-firmware/commit/c2a42399ed509ff1e2b3fca14af62c14fab152b4 for the renaming and https://github.com/trezor/trezor-firmware/commit/ea2af5e51d3b7182c279731c8b1f77fcca37687a and https://github.com/trezor/trezor-firmware/commit/8af5157bf2469250a68c33e3e60c303c950b4146 for introduction of `uart_packet_t` and `spi_packet_t` respectively.

2025-01-06 08:11 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  drv->tx_request_id = -1;
fixed(we don't need to update it in the loop)  https://github.com/trezor/trezor-firmware/commit/e8a083d23efc53d89811fae328f6710ce06d5d5e

2025-01-06 08:11 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  nrf_tx_request_t buffer;
fixed https://github.com/trezor/trezor-firmware/commit/e8a083d23efc53d89811fae328f6710ce06d5d5e

2025-01-06 08:12 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  HAL_GPIO_Init(NRF_IN_GPIO0_PORT, &GPIO_InitStructure);
it will be used later, maybe during the NRF firmware update, of signaling that NRF bootloader is active, i am not sure yet

2025-01-06 10:04 UTC, cepetr requested changes

2025-01-06 10:04 UTC, cepetr commented on core/embed/io/nrf/stm32u5/nrf.c
> +    ;
Unnecessary semicolon

2025-01-06 10:04 UTC, cepetr commented on core/embed/io/nrf/stm32u5/nrf.c
> +  uint8_t len;
Maybe the `len` field could be omitted since it is already part of the `uart_packet_t` and serves the same purpose.

2025-01-06 10:50 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  nrf_tx_request_t buffer = {0};
renamed https://github.com/trezor/trezor-firmware/commit/601953eaaa98ac5fe5a9f08814ada0af48bf84de

2025-01-06 10:50 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  ;
removed https://github.com/trezor/trezor-firmware/commit/601953eaaa98ac5fe5a9f08814ada0af48bf84de

2025-01-06 10:50 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +    ;
removed https://github.com/trezor/trezor-firmware/commit/601953eaaa98ac5fe5a9f08814ada0af48bf84de

2025-01-06 10:50 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +  uint8_t len;
fixed  https://github.com/trezor/trezor-firmware/commit/601953eaaa98ac5fe5a9f08814ada0af48bf84de

2025-01-07 16:45 UTC, mmilata commented on core/embed/io/nrf/inc/io/nrf.h
> +bool nrf_abort_msg(int32_t id);
Aborting messages introduces a bunch of complexity into the queue code, when are we even going to use it?

2025-01-07 16:45 UTC, mmilata commented on core/embed/io/ble/stm32/ble.c
> +  tsqueue_enqueue(&drv->rx_queue, data, len, NULL);
I'm a bit concerned about silently dropping data when a queue is full. Here it's probably OK, we haven't sent application-level ACK yet so Host will time out and resend the packet as if it got lost in the air.

`tx_queue` overflows get reported to the upper layer so that's OK too.

Not sure about `event_queue` - if events get dropped UI will show incorrect BLE state. This could be avoided by UI by ignoring the type of the event and always asking the driver for the entire BLE state, but I think we had this with USB and changed it?

Wondering if we should maintain an overflow counter for every queue in debug builds, along with a function to retrieve them.

2025-01-08 09:08 UTC, TychoVrahe commented on core/embed/util/tsqueue/inc/util/tsqueue.h
> +  int qlen;                  // Queue length
fixed https://github.com/trezor/trezor-firmware/pull/4448/commits/bece4d87e1656373aaacc7313de75986f5504fbd

2025-01-08 09:09 UTC, TychoVrahe commented on core/embed/util/tsqueue/tsqueue.c
> +    queue->entries[i].len = 0;
used the whole `tsqueue_reset` https://github.com/trezor/trezor-firmware/pull/4448/commits/bece4d87e1656373aaacc7313de75986f5504fbd

2025-01-08 09:10 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  tsqueue_enqueue(&drv->event_queue, (uint8_t *)&event, sizeof(event), NULL);
added here https://github.com/trezor/trezor-firmware/pull/4448/commits/bece4d87e1656373aaacc7313de75986f5504fbd

the NRF would otherwise timeout and send the reject itself, but lets not wait as there is no hope in this situation

2025-01-08 09:14 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  nrf_send_msg(NRF_SERVICE_BLE_MANAGER, &cmd, sizeof(cmd), NULL, NULL);
fixed https://github.com/trezor/trezor-firmware/pull/4448/commits/bece4d87e1656373aaacc7313de75986f5504fbd

Note. returning true here doesn't mean that the state was changed, its more of a signal that the driver has received the command, but it can fail during communication with NRF, or the NRF can misbehave.. So the real UI should instead rely on the events/state in most cases

2025-01-08 09:15 UTC, TychoVrahe commented on core/embed/io/nrf/inc/io/nrf.h
> +bool nrf_abort_msg(int32_t id);
Probably will when going to low power modes, there will also be other services that might need that. cc also @cepetr

2025-01-08 21:12 UTC, mmilata approved these changes
nothing else from me

2025-01-09 08:50 UTC, cepetr requested changes

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  drv->timer = systimer_create(ble_loop, NULL);
There are some function calls that may fail. Maybe we could return `bool` and follow  `if (! success) goto cleanup` pattern here.

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +
How about passing `drv` as a context to `systimer_create()`. It seems to me ca bit leaner to me.

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  uint8_t cmd = INTERNAL_CMD_REJECT_PAIRING;
All `ble_send_xxx()` functions could accept a `ble_driver_t*` argument, as they are internal to the module. This approach could help avoid accessing `g_ble_driver`, which feels somewhat inelegant and, in my opinion, should be reserved for public interface functions where it's necessary.

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  nrf_unregister_listener(NRF_SERVICE_BLE);
it seems to me that `nrf_unregister_listener()` should be called before `system_delete()` and `tsqueue_reset()`.

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  drv->initialized = false;
Since `nrf_init()` is called in `ble_init()`, `nrf_free()` should be called here.

2025-01-09 08:50 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  if (!drv->connected || !drv->accept_msgs) {
There are a few callbacks accessing driver variables from the interrupt context (e.g., nrf listeners and systic timer). These variables are also accessed by different functions in the thread context, and it seems to me that some form of synchronization is required.

2025-01-09 13:57 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +        drv->rx_len = 0;
fixed the rx_idx here: https://github.com/trezor/trezor-firmware/commit/7aecc2839812a60218c40ec2efc6b0a8dfa53c34

2025-01-09 13:58 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  uint8_t cmd = INTERNAL_CMD_REJECT_PAIRING;
fixed https://github.com/trezor/trezor-firmware/commit/7aecc2839812a60218c40ec2efc6b0a8dfa53c34

2025-01-09 13:58 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  nrf_unregister_listener(NRF_SERVICE_BLE);
fixed https://github.com/trezor/trezor-firmware/commit/7aecc2839812a60218c40ec2efc6b0a8dfa53c34

2025-01-09 13:59 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  drv->initialized = false;
fixed https://github.com/trezor/trezor-firmware/commit/7aecc2839812a60218c40ec2efc6b0a8dfa53c34

2025-01-09 14:41 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  drv->timer = systimer_create(ble_loop, NULL);
Calling `nrf_deinit()` when `drv->initialized` is not yet set to `true` doesn't work properly. So it looks like it won't work. 

How about implementing `nrf_deinit()` in a way that allows it to be called on a partially initialized driver? In this particular case, this is very simple and then you can use just `goto cleanup`.

2025-01-09 15:14 UTC, TychoVrahe commented on core/embed/io/nrf/stm32u5/nrf.c
> +        drv->rx_len = 0;
Regarding the second part. The startbyte check will sync with the start message, so unless there are periodically messages that contain such byte we will be ok. This is kinda low possibility but i agree that we should probably strive to find more robust solution. However, can we agree to handle this in separate PR?

2025-01-09 15:20 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  drv->timer = systimer_create(ble_loop, NULL);
I think am only calling `nrf_deinit` when its `drv->initialized` is `true`, so it should work (here we are in ble driver and its `initialized` variable is not relevant for `nrf_deinit`). 

I can still of course modify the nrf drivers deinit the way you suggested, but i want to make sure this is what you meant

2025-01-09 15:30 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  if (!drv->connected || !drv->accept_msgs) {
Do you see a place where this actually matters? all i could find is these state variables like `drv->connected`, which in thread context are only read and there is not much point of synchronization, since i.e. after i return from this `ble_can_write` the state can change anyway even if i synchronize in this function

2025-01-10 09:01 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  drv->timer = systimer_create(ble_loop, NULL);
Yes, you are right, it works—I made a decision too quickly. So, it's up to you. Personally, I would go with the approach I proposed, as it might be clearer.

2025-01-10 09:18 UTC, cepetr commented on core/embed/io/ble/stm32/ble.c
> +  if (!drv->connected || !drv->accept_msgs) {
You are right that there isn’t much to synchronize. The issues I see are very subtle and likely won’t cause any problems for now. However, this might change in the future if something else changes.

1. `ble_get_state()` accesses multiple variables and returns them in a structure. These variables are modified in the interrupt context, so we can’t guarantee the consistency of the structure’s content.

2. There’s also an issue (which likely won’t show until we enable LTO) with accessing variables that are modified in the background (in the interrupt context) without a memory barrier (e.g., `irq_lock`/`irq_unlock`).

2025-01-10 10:18 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  drv->timer = systimer_create(ble_loop, NULL);
https://github.com/trezor/trezor-firmware/commit/3075256c27894c170a4b8c611b1b4fe3ee5fc708

2025-01-10 10:27 UTC, TychoVrahe commented on core/embed/io/ble/stm32/ble.c
> +  if (!drv->connected || !drv->accept_msgs) {
as discussed in person, i added synchronization in https://github.com/trezor/trezor-firmware/commit/ed61578f86dbf83044411ddadbbf080229b802cb. This is done in very straightforward way and in every thread function regardless of need.

2025-01-13 15:10 UTC, cepetr approved these changes
utACK

2025-01-14 08:15 UTC, merged