introduce zephyr into firmware monorepo
trezor/trezor-firmware pull request #4449
Opened 2024-12-16 08:52 UTC by TychoVrahe

This PR introduces zephyr, or rather NCS, to firmware monorepo. Zephyr is used for implementing a BLE gateway.

2025-01-23 11:02 UTC, matejcik approved these changes

2025-02-04 13:28 UTC, hiviah commented
I'll add notes as they come to me.

We seem to have `mcuboot overlay` missing in `nordic/trezor/west.yml`, here is a sample one, we need our own fork of mcuboot.

```
    - name: mcuboot
      url: https://github.com/hiviah/mcuboot
      path: bootloader/mcuboot
      revision: edfe1e1465dbc698bf9a195816247913490ab391
```

Also mcboot itself has several boots inside it, IIRC we are using the `boot_serial` one (need to keep in mind when one changes things and things don't appear to change).

2025-02-04 15:48 UTC, hiviah commented on nordic/trezor/README.md
> +west update
Can't yet find a way to have common SDK source so that it's not repeated by each repo clone (since now whole repo build is doubled to some 8 GB). Theoretically only build dir needs to be separate per project, but by  default they clobber over each other.

2025-02-04 17:34 UTC, hiviah requested changes
Not tested on device, but otherwise LGTM.

Just make the `nordic/trezor/west.yml` to point to our mcuboot that needs to be created and check it builds (took the rev id from what we are using to build now with 2.6.2) :

    - name: mcuboot
      url: https://github.com/trezor/mcuboot
      path: bootloader/mcuboot
      revision: daf2946a0f07a14b57bd69d29ac4cdde6f810fb7

2025-02-05 12:09 UTC, TychoVrahe commented on nordic/trezor/README.md
> +west update
we probably could put the west.yml into firmware repo root. then it would initialize the SDK outside of the firmware repo directory, and you could share it, but potential differences between west.yml might cause headaches. 

But you get the additional SDK bloat only per clone when you actually `west init` and `west update`, which might not be that often

2025-02-06 09:03 UTC, cepetr commented on .gitignore
> +/nordic/.west/
How about to move these into `/nordic/.gitignore` folder?

2025-02-06 13:23 UTC, TychoVrahe commented
> We seem to have `mcuboot overlay` missing in `nordic/trezor/west.yml`, here is a sample one, we need our own fork of mcuboot.

Yes, lets do it in separate PR, as we don't have proper repo yet. I created an issue: https://github.com/trezor/trezor-firmware/issues/4585

2025-02-06 21:44 UTC, hiviah approved these changes
Still not tested, separate mcuboot TODO later, but OK for now. NCS will shoot us in foot later anyway.

2025-02-10 16:22 UTC, merged