feat(core/prodtest): Add stwlc38 update from host feature
trezor/trezor-firmware pull request #4462
Opened 2024-12-30 16:23 UTC by kopecdav

This PR adds two new functions to the stwlc38 module.

The first is the patch_and_config function, which uploads the stwlc38 firmware patch and receiver configuration into NVM memory from the host. The second is the read_chip_info function, which reads essential ID and system error information from the stwlc38 registers.

PR includes the firmware patch and configuration in header file  (generated via STM app ) + extends the prodtest WPC commands.

2025-01-02 09:13 UTC, cepetr requested changes

2025-01-02 09:13 UTC, cepetr commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +  ret |= stwlc38_write_fw_register(i2c_bus, STWLC38_FWREG_SYS_CMD_REG, 0x10);
It looks a bit hacky to or subsequent error codes, as `stwlc38_write_fw_registers` returns an error code (enum). Moreover, if the first operation fails, the second one may still be issued, which could lead to unintended behavior.

I would prefer handling the result of each operation individually.

Lastly, the function should return `i2c_status_t` or `bool` if you want to abstract the implementation details.

2025-01-02 09:13 UTC, cepetr commented on core/embed/projects/prodtest/main.c
> +      vcp_println("Some problem occured");
We should print an "ERROR" text here.

2025-01-02 09:13 UTC, cepetr commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +  return timeout == 0 ? ret : STWLC38_ERR_TIMEOUT;
Here, two different types of error codes are being combined.

2025-01-02 13:46 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.h
> +enum stwlc38_op_mode {
Agree, but can we stick to enum instead of struct?

2025-01-02 13:47 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +  i2c_op_t op[] = {
Agree, I'll fix that

2025-01-02 13:48 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                             (STWLC38_HWREG_CUT_ID_REG && 0x0000FF00) >> 8}},
good catch, thanks!

2025-01-02 13:51 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                          .context = NULL,
its a non-static local variable, isn't that dangerous? Isn't there a risk that random values will propagate from stack?

2025-01-02 13:51 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                          .op_count = 2};
Agree, I'll fix that.

2025-01-02 13:52 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.h
> +#define STWLC38_FWREG_OP_MODE_REG 0x000EU
Agree.

2025-01-02 13:52 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.h
> +  uint8_t op_mode;        // Operation mode
Agree.

2025-01-02 13:52 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                                        int32_t len, uint8_t sec_idx) {
yes, make sense

2025-01-02 13:54 UTC, kopecdav commented on core/embed/projects/prodtest/main.c
> +      vcp_println("Some problem occured");
Good point, I'll fix that.

2025-01-02 14:22 UTC, cepetr commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                          .context = NULL,
All omitted fields are automatically initialized as zeros. See this https://stackoverflow.com/questions/10828294/c-and-c-partial-initialization-of-automatic-structure

2025-01-02 14:54 UTC, cepetr commented on core/embed/sys/powerctl/stwlc38/stwlc38.h
> +enum stwlc38_op_mode {
Yes, I meant `typedef enum {`

2025-01-02 16:48 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +                          .context = NULL,
Fixed in [19dba06](https://github.com/trezor/trezor-firmware/pull/4462/commits/19dba060c6739781560c7783f01ca4fb7e00a8f8)

2025-01-02 16:49 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +static int32_t stwlc38_nvm_write_bulk(i2c_bus_t *i2c_bus, const uint8_t *data,
Fixed in [19dba06](https://github.com/trezor/trezor-firmware/pull/4462/commits/19dba060c6739781560c7783f01ca4fb7e00a8f8)

2025-01-02 16:49 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +  ret |= stwlc38_write_fw_register(i2c_bus, STWLC38_FWREG_SYS_CMD_REG, 0x10);
Fixed in [19dba06](https://github.com/trezor/trezor-firmware/pull/4462/commits/19dba060c6739781560c7783f01ca4fb7e00a8f8)

2025-01-02 16:49 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.c
> +  return timeout == 0 ? ret : STWLC38_ERR_TIMEOUT;
Fixed in [19dba06](https://github.com/trezor/trezor-firmware/pull/4462/commits/19dba060c6739781560c7783f01ca4fb7e00a8f8)

2025-01-02 16:50 UTC, kopecdav commented on core/embed/sys/powerctl/stwlc38/stwlc38.h
> +enum stwlc38_op_mode {
Fixed in [19dba06](https://github.com/trezor/trezor-firmware/pull/4462/commits/19dba060c6739781560c7783f01ca4fb7e00a8f8)

2025-01-03 08:25 UTC, cepetr approved these changes
Needs style checks applied and changelog updated; otherwise, LGTM.

2025-01-03 15:30 UTC, merged